version: '2'
services:
  myerp.db:
    image: postgres:9.4
    ports:
      - "172.18.0.2:9032:5432"
    volumes:
#      - "./data/db:/var/lib/postgresql/data"
       - "./init/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_DB=remy-vallet_db_myerp
      - POSTGRES_USER=remy-vallet
      - POSTGRES_PASSWORD=korian77
      
