language: java

jdk:
  - openjdk11

services:
#  - docker

addons:
  sonarcloud:
    organization: "rvallet"

before_script:
#  - docker-compose -f docker/dev/docker-compose.yml up -d
#  - docker inspect --format='{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq)
  - cd ./src

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
#  - mvn clean -P test-consumer,test-business org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=rvallet_ocp9-projetB4 -Dsonar.login=de21cc28458176f9a5cc3287a75fbb28ce645580
  - mvn clean -P org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=rvallet_ocp9-projetB4 -Dsonar.login=de21cc28458176f9a5cc3287a75fbb28ce645580

after_script:
#  - docker-compose -f ../docker/dev/docker-compose.yml stop
#  - docker-compose -f ../docker/dev/docker-compose.yml rm -f

git:
  depth: false

notifications:
  email: false