language: java
sudo: false # (faster builds)
jdk:
  - openjdk8

before_script:
  - cd ./src
#  - psql -c 'create database XXX;' -U postgres

script:
  - mvn test -B
#  - mvn xxx test-business, test-consumer
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN=:uuid-repo-token
#CODECOV_TOKEN='2ddf21b4-1ac3-409d-9623-31953bbaf905'

services:
  - postgresql